import{a as f,S as y,i as h}from"./assets/vendor-31f4717e.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&o(c)}).observe(document,{childList:!0,subtree:!0});function a(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(t){if(t.ep)return;t.ep=!0;const r=a(t);fetch(t.href,r)}})();const g="https://pixabay.com/api/",v="45320623-f265cdcadbbe2c6a410e5ea22";async function L(e,s=1){try{return(await f.get(g,{params:{key:v,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:15}})).data}catch(a){throw console.error("Error fetching images:",a),a}}const w=new y(".gallery-list a",{captions:!0,captionsData:"alt",captionsDelay:250});function x(e){const s=document.querySelector(".gallery-list");let a=e.hits.map(o=>`<div class="image-wrapper">
    <a href="${o.largeImageURL}">
    <img class="gallery-img" src="${o.webformatURL}" alt="${o.tags}"></img>
    </a>
    <div class="text-wrapper">
    <div class="text-item"><h5 class="text-header">Likes</h5><p class="text-paragraph">${o.likes}</p></div>
    <div class="text-item"><h5 class="text-header">Views</h5><p class="text-paragraph">${o.views}</p></div>
    <div class="text-item"><h5 class="text-header">Comments</h5><p class="text-paragraph">${o.comments}</p></div>
    <div class="text-item"><h5 class="text-header">Downloads</h5><p class="text-paragraph">${o.downloads}</p></div>
    </div>
    </div>`).join("");s.insertAdjacentHTML("beforeend",a),w.refresh()}function b(){const e=document.querySelector(".gallery-list");e.innerHTML=""}const p=document.querySelector(".form-gallery"),S=document.querySelector(".form-gallery-input"),l=document.querySelector(".loader"),d=document.querySelector(".load-more"),i=document.querySelector(".scroll-to-top");let n=1,u="";p.addEventListener("submit",q);d.addEventListener("click",T);i.addEventListener("click",$);async function q(e){e.preventDefault(),b(),l.classList.remove("hidden"),u=S.value.trim(),n=1,await m(),p.reset()}async function T(){n+=1,await m()}async function m(){try{const e=await L(u,n);if(l.classList.add("hidden"),e.total===0||u===""){h.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"});return}x(e),e.hits.length===0||n*15>=e.totalHits?(d.classList.add("hidden"),h.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."})):d.classList.remove("hidden"),E(),P()}catch(e){console.error(e),l.classList.add("hidden")}}function E(){const{height:e}=document.querySelector(".gallery-list").firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}function P(){window.scrollY>1e3?i.classList.remove("hidden"):i.classList.add("hidden")}function $(){window.scrollTo({top:0,behavior:"auto"})}window.addEventListener("scroll",i);
//# sourceMappingURL=commonHelpers.js.map
