import{a as f,S as y,i as h}from"./assets/vendor-31f4717e.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const d of r.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&s(d)}).observe(document,{childList:!0,subtree:!0});function a(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=a(t);fetch(t.href,r)}})();const g="https://pixabay.com/api/",L="45320623-f265cdcadbbe2c6a410e5ea22";async function v(e,o=1){try{return(await f.get(g,{params:{key:L,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}})).data}catch(a){throw console.error("Error fetching images:",a),a}}const w=new y(".gallery-list a",{captions:!0,captionsData:"alt",captionsDelay:250});function x(e){const o=document.querySelector(".gallery-list");let a=e.hits.map(s=>`<div class="image-wrapper">
    <a href="${s.largeImageURL}">
    <img class="gallery-img" src="${s.webformatURL}" alt="${s.tags}"></img>
    </a>
    <div class="text-wrapper">
    <div class="text-item"><h5 class="text-header">Likes</h5><p class="text-paragraph">${s.likes}</p></div>
    <div class="text-item"><h5 class="text-header">Views</h5><p class="text-paragraph">${s.views}</p></div>
    <div class="text-item"><h5 class="text-header">Comments</h5><p class="text-paragraph">${s.comments}</p></div>
    <div class="text-item"><h5 class="text-header">Downloads</h5><p class="text-paragraph">${s.downloads}</p></div>
    </div>
    </div>`).join("");o.insertAdjacentHTML("beforeend",a),w.refresh()}function b(){const e=document.querySelector(".gallery-list");e.innerHTML=""}const p=document.querySelector(".form-gallery"),S=document.querySelector(".form-gallery-input"),n=document.querySelector(".loader"),i=document.querySelector(".load-more"),c=document.querySelector(".scroll-to-top");let l=1,u="";p.addEventListener("submit",q);i.addEventListener("click",T);c.addEventListener("click",$);async function q(e){e.preventDefault(),b(),n.classList.remove("hidden"),i.classList.add("hidden"),u=S.value.trim(),l=1,await m(),p.reset()}async function T(){l+=1,i.classList.add("hidden"),n.classList.remove("hidden"),await m()}async function m(){try{const e=await v(u,l);if(n.classList.add("hidden"),e.total===0||u===""){h.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}),i.classList.add("hidden");return}x(e),e.hits.length===0||l*15>=e.totalHits?(i.classList.add("hidden"),h.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."})):i.classList.remove("hidden"),E(),P()}catch(e){console.error(e),n.classList.add("hidden")}}function E(){const{height:e}=document.querySelector(".gallery-list").firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}function P(){window.scrollY>1e3?c.classList.remove("hidden"):c.classList.add("hidden")}function $(){window.scrollTo({top:0,behavior:"auto"})}window.addEventListener("scroll",c);
//# sourceMappingURL=commonHelpers.js.map
